name: flutter_devfest_gdg_newdelhi
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+3

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flare_flutter:
  intl:
  provider:
  shared_preferences:
  url_launcher:
  share:
  circular_reveal_animation:
  video_player:
  http:
  connectivity:
  flutter_spinkit: ^3.1.0
  cached_network_image:
  flutter_advanced_networkimage:



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/gdg_banner.jpg
    - assets/gdg_logo.png
    - assets/model.jpg
    - assets/facebook light theme.png
    - assets/linkdin light theme.png
    - assets/twitter loght theme.png
    - assets/youtube light theme.png
    - assets/github.png
    - assets/logo-light.png
    - assets/logo_dark.png
    - assets/agenda.png
    - assets/speaker.png
    - assets/sponsors.png
    - assets/team.png
    - assets/bulb_on.png
    - assets/bulb_off.png
    - assets/button.png
    - assets/arrow-blue.png
    - assets/nouserprofile.png
    - assets/Arrow light theme.png
    - assets/arrowdarktheme.png
    - assets/GDG-Cloud-New-Delhi.png
    - assets/GDG-New-Delhi.png
    - assets/WTM-Delhi.png
    - assets/gdg.png
    - assets/noprofileuser.png
    - assets/share light theme.png
    - assets/share-dark-theme.png
    - assets/loader.flr
    - assets/loader2.flr
    - assets/video/splashvideo1.mp4
    - assets/video/splash.mp4




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
